services:
  web:
    build: .
    image: api-music
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql_psycopg2
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=music
      - DB_USER=postgres
      - DB_PASS=s3mS3NH4
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=music
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s3mS3NH4
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}