# Generated by Django 5.1.1 on 2024-10-31 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=255)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('title', models.CharField(db_column='tx_title', max_length=255)),
                ('date', models.DateField(db_column='dt_date')),
                ('author', models.ForeignKey(db_column='id_author', on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('title', models.CharField(db_column='tx_title', max_length=255)),
                ('duration', models.TimeField(db_column='tm_duration')),
                ('album', models.ForeignKey(db_column='id_album', on_delete=django.db.models.deletion.CASCADE, to='api.album')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
                'db_table': 'music',
            },
        ),
    ]
