# Generated by Django 5.1.1 on 2024-10-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_unacent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.DurationField(db_column='tm_duration'),
        ),
    ]
