# Generated by Django 2.1.2 on 2018-11-28 01:09
import base64

from django.contrib.auth.models import User
from django.db import migrations




def create_initial_user(apps, schema_editor):
    User.objects.create_superuser(
        username='admin',
        password=base64.b64decode('VHdJdTdhbjQzQHYx'.encode()).decode(),
    )



class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_alter_music_duration'),
    ]

    operations = [
        migrations.RunPython(create_initial_user)
    ]
